<div class="list-group">
					
	<a href="home.php" class="list-group-item list-group-item-action <?php echo showActive('home'); ?>">
		<div class="media">
			<div class="media-left align-self-center"></div>
			<div class="media-body align-self-center">Home</div>
		</div>
	</a>

	<a href="task1.php" class="list-group-item list-group-item-action <?php echo showActive('donate'); ?>">
		<div class="media">
			<div class="media-left align-self-center"></div>
			<div class="media-body align-self-center">Donate</div>
		</div>
	</a>
	
	<a href="task2.php" class="list-group-item list-group-item-action <?php echo showActive('update'); ?>">
		<div class="media">
			<div class="media-left align-self-center"></div>
			<div class="media-body align-self-center">Update Funding</div>
		</div>
	</a>

	<a href="task3.php" class="list-group-item list-group-item-action <?php echo showActive('delete'); ?>">
		<div class="media">
			<div class="media-left align-self-center"></div>
			<div class="media-body align-self-center">Delete Funding</div>
		</div>
	</a>

</div>