<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">Thank You</h4>
  <p>
  	Dear Mr/Miss/Mrs <?php echo $surname; ?>
  	<br />
		We As The SMU Advancement & Internationalisation Office Would Like To Thank For The Contribution You Have Made!
		Through This Donation You Have Changed A Student's Life In Giving Him/Her An Opportunity To Further Their Studies.
		<br />
		<br />
		Thank You
		Management
		</p>

  <div class="space-small"></div>
  <a class="btn btn-success btn-lg btn-block" href="Thank-You-Letter.txt" download>Donation Appreciation Letter</a>

</div>